class TaskError(Exception): ...


class TaskInvariantError(TaskError): ...


class InvalidIDError(TaskInvariantError): ...


class InvalidDescriptionError(TaskInvariantError): ...


class InvalidPriorityError(TaskInvariantError): ...


class InvalidStatusError(TaskInvariantError): ...


class InvalidStatusTransitionError(TaskInvariantError): ...


class InvalidTimestampError(TaskInvariantError): ...


class ReadOnlyFieldError(TaskInvariantError): ...
